name: Watch Files

on:
  push:
    paths:
      - 'configure-pm2.md'
      - 'table-of-contents.md'
      - 'debian-bullseye-upgrade-script.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Debug
       env:
         MODIFIED: ${{ toJson(github.event.head_commit.modified) }}
       run: echo $MODIFIED

     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Bullseye_Upgrade_Script
        event-type: file-changed
        client-payload: '{ "message": "configure-pm2.md changed" }'  

     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Configure_PM2
        event-type: file-changed
        client-payload: '{ "message": "configure-pm2.md changed" }'
        
    

